### ISSUE TITLE
MAJ ?

### ISSUE THREAD

**Issue by WhiteSkyAngel** [Emmanuel-Novus/anti-raid#1]
Possibilité de mettre le bot à jour ?

Pleins de choses qui fonctionnent pas, notamment, quand on met aucune raison pour le ban, ça mets pas "Aucune raison" mais ça met rien du tout :/

**Comment by Emmanuel-Novus-zz** [comment]
Soon.

**Comment by Emmanuel-Novus-zz** [comment]
### **The new version is now available!**
